services:
    aetheryte-postgres:
        build:
            context: postgres
            dockerfile: Dockerfile
        volumes:
            - aetheryte_postgres:/var/lib/postgresql/data/
        networks:
            transcendence:
                ipv4_address: 172.20.0.3
        environment:
            POSTGRES_DB: ${A_POSTGRES_DB}
            POSTGRES_USER: ${A_POSTGRES_USER}
            POSTGRES_PASSWORD: ${A_POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${A_POSTGRES_USER} -d ${A_POSTGRES_DB}'"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    aetheryte-python:
        build:
            context: python
            dockerfile: Dockerfile
        volumes:
            - ../src:/app
        networks:
            transcendence :
                ipv4_address: 172.20.0.2
        # healthcheck:
        #     test: curl --fail https://localhost:8000/ || exit 1
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
        restart: on-failure