services:
    aetheryte-postgres:
        build:
            context: postgres
            dockerfile: Dockerfile
        volumes:
            - aetheryte_postgres:/var/lib/postgresql/data/
        networks:
            transcendence:
                ipv4_address: 172.20.0.3
        environment:
            POSTGRES_DB: ${AETHERYTE_POSTGRES_NAME}
            POSTGRES_USER: ${ROOT_USER}
            POSTGRES_PASSWORD: ${ROOT_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${ROOT_USER} -d ${AETHERYTE_POSTGRES_NAME}'"]
            interval: 10s
            timeout: 5s
            retries: 10
        restart: unless-stopped

    aetheryte-python:
        build:
            context: python
            dockerfile: Dockerfile
        volumes:
            - ../app:/app
        networks:
            transcendence :
                ipv4_address: 172.20.0.2
        environment:
            AETHERYTE_POSTGRES_DB: ${AETHERYTE_POSTGRES_NAME}
            AETHERYTE_POSTGRES_USER: ${ROOT_USER}
            AETHERYTE_POSTGRES_PASSWORD: ${ROOT_PASSWORD}
            AETHERYTE_POSTGRES_IP: ${AETHERYTE_POSTGRES_IP}
            AETHERYTE_POSTGRES_PORT: ${AETHERYTE_POSTGRES_PORT}
            AETHERYTE_DJANGO_SECRET_KEY: ${AETHERYTE_DJANGO_SECRET_KEY}

        healthcheck:
            test: curl --fail http://localhost:8000/api/user || exit 1
            interval: 10s
            timeout: 5s
            retries: 10
        restart: on-failure